<<<<<<< HEAD
language: python
python:
  - 3.8.5
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
script:
  - pytest --cov=com.kuma com/kuma/test/
=======
pytest --cov=com.kuma com/kuma/test/
>>>>>>> 14ec3eead5859649e53dc85abf9d45db209ef561
